version: "3"
services:

  mongodb:
    image: 'bitnami/mongodb:latest'
    restart: unless-stopped
    env_file: .env
    environment:
      MONGODB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MONGODB_DATABASE: ${DATABASE_NAME}
      MONGODB_USERNAME: ${DATABASE_USERNAME}
      MONGODB_PASSWORD: ${DATABASE_PASSWORD}
      MONGODB_DEFAULT_PORT_NUMBER: ${MONGODB_DEFAULT_PORT_NUMBER}
    volumes:
      - "mongodb_data:/bitnami/mongodb"
      - "./db/mongo:/docker-entrypoint-initdb.d"
    networks:
      - udNodeJs
    ports:
      - "${MONGODB_DEFAULT_PORT_NUMBER}:${MONGODB_DEFAULT_PORT_NUMBER}"



  udNodeJsDB:
    image: docker.io/bitnami/mariadb:latest
    restart: unless-stopped
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - "mariadb_data:/bitnami/mariadb"
      - "./db/mysql:/docker-entrypoint-initdb.d"
    networks:
      - udNodeJs

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: udNodeJsDB
      DATABASE_USER: ${DATABASE_ROOT_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_ALLOW_NO_PASSWORD: false
      PHPMYADMIN_ALLOW_ARBITRARY_SERVER: yes
    ports:
      - "88:8080"
    networks:
      - udNodeJs
    depends_on:
      - udNodeJsDB

volumes:
  mariadb_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  udNodeJs:
    name: UDNodeJs
    driver: bridge
